### ISSUE TITLE
XML file encoding bug?

### ISSUE THREAD

**Issue by Sorenant** [matortheeternal/mod-analyzer#12]
Analyzing [Hidden Hideouts of Skyrim City Edition Merged](http://www.nexusmods.com/skyrim/mods/53329/?) fails using Mod Analyzer 1.7.2 launched from Mod Organizer 1.3.11 running on Windows 10. Here's the log:

```
Analyzing Hidden Hideouts of Skyrim City Edition - Merged-53329-2-0.7z...
Calculating MD5 Hash.
Parsing FOMOD Options
Found FOMOD Config at fomod/ModuleConfig.xml
FOMOD Config Extracted

There is no Unicode byte order mark. Cannot switch to Unicode.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
   at System.Xml.XmlTextReaderImpl.CheckEncoding(String newEncodingName)
   at System.Xml.XmlTextReaderImpl.ParseXmlDeclaration(Boolean isTextDecl)
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at ModAnalyzer.Domain.FomodConfig..ctor(String xmlPath)
   at ModAnalyzer.Domain.ModAnalyzerService.AnalyzeFomodArchive(IArchive archive)
   at ModAnalyzer.Domain.ModAnalyzerService.AnalyzeArchive(IArchive archive, ModOption modOption)
   at ModAnalyzer.Domain.ModAnalyzerService.BackgroundWork(Object sender, DoWorkEventArgs e)
Analysis failed.
```

**Comment by matortheeternal** [comment]
Sounds like an issue with the XML file encoding?  That's odd.  I'll look into this, thanks!

**Comment by matortheeternal** [comment]
Alright, I've found the source of the problem and pushed a fix to master.  Will make a new version available later tonight.
