### ISSUE TITLE
Could not load file or assembly 'libbsa.dll' or one of its dependencies. The specified module could not be found.

### ISSUE THREAD

**Issue by ghost** [matortheeternal/mod-analyzer#15]
Getting this error while trying to analyze '[Horns Are Forever](http://www.nexusmods.com/skyrim/mods/20861/?)'
using Update 1.8.1
OS is win10
OldSkyrim mod

> Analyzing Horns Are Forever-20861-1-0.rar...
Calculating MD5 Hash.
Data\hornsareforever.bsa
Data\hornsareforever.esp
readme.txt

>Getting assets from bsas\hornsareforever.bsa...

>Could not load file or assembly 'libbsa.dll' or one of its dependencies. The specified module could not be found.
   at ModAnalyzer.Domain.AssetArchiveAnalyzer.GetBSAAssets(String bsaPath)
   at ModAnalyzer.Domain.AssetArchiveAnalyzer.GetAssetPaths(IArchiveEntry assetArchive)
   at ModAnalyzer.Domain.ModAnalyzerService.AnalyzeEntries()
   at ModAnalyzer.Domain.ModAnalyzerService.BackgroundWork(Object sender, DoWorkEventArgs e)
Analysis failed.

Tried a new install, didn't work with same error.
However it did work on '[Bigger Argonian Tails](http://www.nexusmods.com/skyrim/mods/17339/?)' 

Edit: seems to also occur on '[Enchanted Arsenal](http://www.nexusmods.com/skyrim/mods/56614/?)'

>Analyzing Enchanted Arsenal-56614-2-23.7z...
Calculating MD5 Hash.
SKSE\Plugins\FISS\Enchanted Arsenal\Preset 1.xml
SKSE\Plugins\FISS\Enchanted Arsenal\Preset 2.xml
SKSE\Plugins\FISS\Enchanted Arsenal\Preset 3.xml
SKSE\Plugins\FISS\Enchanted Arsenal\Preset 4.xml
SKSE\Plugins\FISS\Enchanted Arsenal\Preset 5.xml
SKSE\Plugins\FISS\Enchanted Arsenal\Preset Defaults.xml
SKSE\Plugins\FISS\Enchanted Arsenal\readme.txt
EnchantedArsenal.bsa
EnchantedArsenal.esp
SKSE\Plugins\EnchArsenal.dll
 
>Extracting BSA at EnchantedArsenal.bsa...
EnchantedArsenal.bsa extracted, analyzing entries...
Getting assets from bsas\EnchantedArsenal.bsa...

>Could not load file or assembly 'libbsa.dll' or one of its dependencies. The specified module could not be found.
   at ModAnalyzer.Domain.AssetArchiveAnalyzer.GetBSAAssets(String bsaPath)
   at ModAnalyzer.Domain.AssetArchiveAnalyzer.GetAssetPaths(IArchiveEntry assetArchive)
   at ModAnalyzer.Domain.ModAnalyzerService.AnalyzeEntries()
   at ModAnalyzer.Domain.ModAnalyzerService.BackgroundWork(Object sender, DoWorkEventArgs e)
Analysis failed.

**Comment by matortheeternal** [comment]
Bug with libbsa.dll.  I'm pushing a hotfix release now.
